In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

/home/ma/.bin/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.randint(2,3,4)

array([2, 2, 2, 2])

In [8]:
np.random.rand(2,3)

array([[0.68406318, 0.00757117, 0.03674772],
       [0.87360138, 0.79175997, 0.17097955]])

In [ ]:
np.arange(19)